export const SET_CONFIG_GID = 'SET_CONFIG_GID';
export const SET_CUSTOM_GID = 'SET_CUSTOM_GID';
export const SET_CONFIG_WIDGET = 'SET_CONFIG_WIDGET';
export const FETCH_GRID_DATA = 'FETCH_GRID_DATA';
export const FETCH_GRID_FAILURE = 'FETCH_GRID_FAILURE';
