export const CONFIG_ENTRY_ADD = 'CONFIG_ENTRY_ADD';
export const CONFIG_ENTRY_EDIT = 'CONFIG_ENTRY_EDIT';
export const CONFIG_ENTRY_CLOSE = 'CONFIG_ENTRY_CLOSE';
export const CONFIG_ENTRY_RESET = 'CONFIG_ENTRY_RESET';